#!/bin/bash

#	BSD 3-Clause License
#
#	Copyright (c) 2026, Gussak<https://github.com/Gussak>
#
#	Redistribution and use in source and binary forms, with or without
#	modification, are permitted provided that the following conditions are met:
#
#	1. Redistributions of source code must retain the above copyright notice, this
#		 list of conditions and the following disclaimer.
#
#	2. Redistributions in binary form must reproduce the above copyright notice,
#		 this list of conditions and the following disclaimer in the documentation
#		 and/or other materials provided with the distribution.
#
#	3. Neither the name of the copyright holder nor the names of its
#		 contributors may be used to endorse or promote products derived from
#		 this software without specific prior written permission.
#
#	THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#	AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#	IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
#	DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
#	FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
#	DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
#	SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
#	CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
#	OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
#	OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

set -Eeu

function FUNCdetectPidToPause() { # the one that has no focus
	#set -x
	nWFocId="$(xdotool getwindowfocus)"&&:
	nWFocNm="$(xdotool getwindowname $nWFocId)"&&:
	nWFocPid="$(xdotool getwindowpid $nWFocId)"&&:
	
	bPauseAll=false
	if ! strWineprefixWFocus="$(strings /proc/$nWFocPid/environ |grep WINEPREFIX)";then
		bPauseAll=true;
	fi
	
	# multidimentional array simulated: [PidGM] = PidFM WindowID WINEPREFIX (the link between them is WINEPREFIX)
	declare -g anPidGm=($(pgrep -f "Dark Messiah.*mm.exe"))
	declare -g aPidGm_PidFM=() # the PidFM is from explorer.exe (filemanager FM) and not from the game as wine is running in desktop single window mode
	declare -g aPidGm_WindowID=()
	declare -g aPidGm_WINEPREFIX=()
	declare -g aPidGm_bFocus=()
	
	for nPidGm in "${anPidGm[@]}";do
		strWineprefixGm="$(strings /proc/$nPidGm/environ |grep WINEPREFIX)"
		aPidGm_WINEPREFIX[$nPidGm]="$strWineprefixGm"
	done
	
	mapfile -t astrLn < <(wmctrl -l -p |grep "Wine Desktop" |awk '{print "_nW=" $1 ";_nPidFM=" $3 ";"}')
	for strLn in "${astrLn[@]}";do eval "${strLn}";
		strWineprefixFm="$(strings /proc/$_nPidFM/environ |grep WINEPREFIX)"
		#for((i=0;i<${#aPidGm_WINEPREFIX[@]};i++));do
		#echo "DEBUG:${!aPidGm_WINEPREFIX[@]}"
		#declare -p _nPidFM _nW
		for nPidGm in ${!aPidGm_WINEPREFIX[@]};do
			#echo "if [[ \"$strWineprefixFm\" == \"${aPidGm_WINEPREFIX[$nPidGm]}\" ]];then"
			if [[ "$strWineprefixFm" == "${aPidGm_WINEPREFIX[$nPidGm]}" ]];then
				aPidGm_PidFM[$nPidGm]="$_nPidFM"
				aPidGm_WindowID[$nPidGm]="$(printf %d $_nW)"
				if((nWFocId==${aPidGm_WindowID[$nPidGm]}));then aPidGm_bFocus[$nPidGm]=true; else aPidGm_bFocus[$nPidGm]=false; fi
			fi
		done
		#declare -p aPidGm_PidFM
	done
	
	#nPidGmExecFocus=0
	##for((i=0;i<${#anPidGm[@]};i++));do
	#for nPidGm in "${anPidGm[@]}";do
		#strWineprefixGm="$(strings /proc/$nPidGm/environ |grep WINEPREFIX)"
		#if [[ "$strWineprefixGm" == "$strWineprefixWFocus" ]];then
			#nPidGmExecFocus=$nPidGm
			#break;
		#fi
	#done
	#nPidGmExecOther=0
	#for nPidGm in "${anPidGm[@]}";do
		#if((nPidGmExecFocus == nPidGm));then continue;fi
		#nPidGmExecOther=$nPidGm
		#break;
	#done
	
	#declare -p nWFocId nWNm nWPid anPidGm nPidGmExecFocus >&2
	declare -p anPidGm aPidGm_PidFM aPidGm_WindowID aPidGm_WINEPREFIX aPidGm_bFocus
	
	#declare -g FUNCdetectPidToPause_nPidGmNoFocus=$nPidGmExecOther
	#declare -g FUNCdetectPidToPause_nWindowNoFocus=$nWindowOther
};export -f FUNCdetectPidToPause

function FUNCtest() {
	FUNCdetectPidToPause
}
if [[ "${1-}" == --test ]];then FUNCtest;exit;fi

egrep "[#]help" "$0"

: ${strGameSubFolderCore:="WriteNewDataHereOnly"};export strGameSubFolderCore #help I know of: mm custom AddOn(overhaul mod) and the new one WriteNewDataHereOnly

: ${strFlHint:="$HOME/Wine/DarkMessiahOfMightAndMagic.win32/drive_c/Games/Dark Messiah Might and Magic Single Player/${strGameSubFolderCore}/demoheader.tmp"};export strFlHint #help overrides strGameSubFolderCore

: ${nIgnoreTinyStringsSize:=10};export nIgnoreTinyStringsSize #help these tiny strings are probably useless here TODO: just filter out if not: [0-9a-zA-Z_]*

function FUNCstringsDump() { #help <index> use this to dump demoheader.tmp strings for clues
	local lnIndex="${1}"; #help the backup index generated by ... . must be like ex.: 000000007 (fixed 9 decimal places with zeros on the left)
	strings "${strFlHint}.${lnIndex}.bkp" \
		|tr -d ' \t\r' \
		|sed -r -e 's@^.{1,'${nIgnoreTinyStringsSize}'}$@@g' \
		|sort -u >"${strFlHint}.${lnIndex}.bkp.Strings.txt"
};export -f FUNCstringsDump

function FUNCmonitorChanges() {
	local lnSz=0;
	local lnCount=1
	
	local lfLoopDelay
	: ${lfLoopDelay:=0.33} #help_FUNCmonitorChanges
	
	#local lstrFlNewest="$(ls -1tr "${strFlHint}"*"bkp" |tail -n 1)"&&:
	local lstrFlNewest="$(ls -1 "${strFlHint}"*"bkp" |sort |tail -n 1)"&&:
	declare -p lstrFlNewest
	
	if [[ -n "$lstrFlNewest" ]];then
		local lnIndex="${lstrFlNewest#${strFlHint}.}"
		lnIndex="${lnIndex%.bkp}"
		lnIndex=$((10#$lnIndex))
		((lnIndex++))&&: #next
		declare -p lnIndex
		lnCount=$lnIndex
	fi
	
	while true;do 
		local lnSzNew=$(stat -c %s "$strFlHint");
		if(( lnSz != lnSzNew ));then
			local lstrIndex="$(printf %09d $lnCount)"
			cp -vf "$strFlHint" "${strFlHint}.${lstrIndex}.bkp";
			FUNCstringsDump "${lstrIndex}"
			((lnCount++))&&:;
			ls -l "$strFlHint"*"${lstrIndex}"*;
			lnSz=$lnSzNew;
		fi;
		sleep ${lfLoopDelay};
	done
};export -f FUNCmonitorChanges

if [[ "${1-}" == -m ]];then #help monitor changes and dump strings
	#FUNCmonitorChanges
	(xterm -e FUNCmonitorChanges & disown)
	exit
fi

export nScrWhalf=$(($(xdotool getdisplaygeometry |awk '{print $1}') / 2 ))

function FUNCpauseAfterLoad() {
	#set -x
	: ${strTextHint:="hltv_status"} #help this shows up on the last writing to that file, after that you only need to wait for 5s!
	: ${bPauseOnlyNoFocusInstance:=false} #help :D
	while true;do
		nThisRunTime=$(date +%s)
		while true;do
			echo
			echo "=============================== $(date) ================================"
			sleep 1
			
			FUNCdetectPidToPause
			#anPidGm=($(pgrep -f "C:[\].*[\]mm.exe"))
			
			: ${bExitIfGameExits:=false} #help
			if $bExitIfGameExits;then
				if ! ps -p ${anPidGm[@]};then exit;fi
			fi
			
			if(( $(stat -c %Y "$strFlHint") < nThisRunTime ));then
				continue
			fi
			if ! egrep "${strTextHint}" "$strFlHint";then
				continue;
			fi
			: ${fSleepAfterHintFound:=3.0} #help
			read -n 1 -t $fSleepAfterHintFound -p "hit a key to SIGSTOP game"
			
			#FUNCdetectPidToPause
			for nPidGm in "${anPidGm[@]}";do
				#if $bPauseOnlyNoFocusInstance && ((FUNCdetectPidToPause_nPidNoFocus != 0 && nPidGm != FUNCdetectPidToPause_nPidNoFocus));then continue;fi
				if $bPauseOnlyNoFocusInstance && ${aPidGm_bFocus[$nPidGm]};then continue;fi # ignores focused window
				
				kill -SIGSTOP $nPidGm
				if which ScriptEchoColor;then echoc --say "Game Loaded";fi
				#while ! yad --title="DarkMessiah:helper" --text="Dark Messiah of MM\n Game Finished Loading\n SigStopped\n Continue NOW?" --geometry=1x1+$nScrWhalf+0 --undecorated;do :;done; # not --on-top because it cant be too small :(
				#while ! yad --geometry=1x1+$nScrWhalf+0 --title="DarkMessiah:helper" --center --no-buttons;do :;done; # not --on-top because it cant be too small :(
				yad --geometry=500x1+$nScrWhalf+0 --title="DarkMessiah:FinishedLoading:${nPidGm}" --on-top --no-buttons --no-focus #unable to popup below :(, it should not receive imediate focus but should be focusable!!! unable to prevent it starting --on-top, so keep it there; no buttons, just hold the flow here
				kill -SIGCONT $nPidGm
				xdotool windowfocus ${aPidGm_WindowID[$nPidGm]}
			done
			
			break # to update nThisRunTime for the next game load
		done
	done
};export -f FUNCpauseAfterLoad;

#set -x
if ! pgrep -fa DarkMessiah_FUNCpauseAfterLoad;then
	: ${bXterm:=true}
	if $bXterm;then
		(xterm -title DarkMessiah_FUNCpauseAfterLoad -e bash -c "FUNCpauseAfterLoad" & disown);
	else
		FUNCpauseAfterLoad
	fi
fi
