#!/bin/bash

#	BSD 3-Clause License
#
#	Copyright (c) 2026, Gussak<https://github.com/Gussak>
#
#	Redistribution and use in source and binary forms, with or without
#	modification, are permitted provided that the following conditions are met:
#
#	1. Redistributions of source code must retain the above copyright notice, this
#		 list of conditions and the following disclaimer.
#
#	2. Redistributions in binary form must reproduce the above copyright notice,
#		 this list of conditions and the following disclaimer in the documentation
#		 and/or other materials provided with the distribution.
#
#	3. Neither the name of the copyright holder nor the names of its
#		 contributors may be used to endorse or promote products derived from
#		 this software without specific prior written permission.
#
#	THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#	AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#	IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
#	DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
#	FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
#	DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
#	SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
#	CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
#	OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
#	OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

set -Eeu -o pipefail

aPidVsWindowList=()
function FUNCdetectPidToPause() { # the one that has no focus
	#set -x
	nWFoc="$(xdotool getwindowfocus)"&&:
	nWNm="$(xdotool getwindowname $nWFoc)"&&:
	nWPid="$(xdotool getwindowpid $nWFoc)"&&:
	
	strWineprefixFocus="$(strings /proc/$nWPid/environ |grep WINEPREFIX)"
	
	anPid=($(pgrep -f "Dark Messiah.*mm.exe"))
	wmctrl -l -p |grep "Wine Desktop" |awk '{print "_nW=" $1 ";_nPidFM=" $3 ";"}' |while read strLn;do
		eval "${strLn}";
		aPidVsWindowList[${_nPidFM}]="${_nW}" # the pid is from explorer.exe (filemanager FM) and not from the game as wine is running in desktop single window mode
	done
	
	strWineprefixExecutableFocus=""
	nPidExecFocus=0
	#for((i=0;i<${#anPid[@]};i++));do
	for nPid in "${anPid[@]}";do
		strWineprefixExecutable="$(strings /proc/$nPid/environ |grep WINEPREFIX)"
		if [[ "$strWineprefixExecutable" == "$strWineprefixFocus" ]];then
			strWineprefixExecutableFocus="$strWineprefixExecutable"
			nPidExecFocus=$nPid
			break;
		fi
	done
	nPidExecOther=0
	for nPid in "${anPid[@]}";do
		if((nPidExecFocus == nPid));then continue;fi
		nPidExecOther=$nPid
		break;
	done
	
	declare -p nWFoc nWNm nWPid anPid strWineprefixExecutableFocus nPidExecFocus >&2
	
	declare -g FUNCdetectPidToPause_nPidNoFocus=$nPidExecOther
	declare -g FUNCdetectPidToPause_nWindowNoFocus=$nWindowOther
};export -f FUNCdetectPidToPause

function FUNCtest() {
	FUNCdetectPidToPause
}
if [[ "${1-}" == --test ]];then FUNCtest;exit;fi

egrep "[#]help" "$0"

: ${strGameSubFolderCore:="WriteNewDataHereOnly"};export strGameSubFolderCore #help I know of: mm custom AddOn(overhaul mod) and the new one WriteNewDataHereOnly

: ${strFlHint:="$HOME/Wine/DarkMessiahOfMightAndMagic.win32/drive_c/Games/Dark Messiah Might and Magic Single Player/${strGameSubFolderCore}/demoheader.tmp"};export strFlHint #help overrides strGameSubFolderCore

: ${nIgnoreTinyStringsSize:=10};export nIgnoreTinyStringsSize #help these tiny strings are probably useless here TODO: just filter out if not: [0-9a-zA-Z_]*

function FUNCstringsDump() { #help <index> use this to dump demoheader.tmp strings for clues
	local lnIndex="${1}"; #help the backup index generated by ... . must be like ex.: 000000007 (fixed 9 decimal places with zeros on the left)
	strings "${strFlHint}.${lnIndex}.bkp" \
		|tr -d ' \t\r' \
		|sed -r -e 's@^.{1,'${nIgnoreTinyStringsSize}'}$@@g' \
		|sort -u >"${strFlHint}.${lnIndex}.bkp.Strings.txt"
};export -f FUNCstringsDump

function FUNCmonitorChanges() {
	local lnSz=0;
	local lnCount=1
	
	local lfLoopDelay
	: ${lfLoopDelay:=0.33} #help_FUNCmonitorChanges
	
	#local lstrFlNewest="$(ls -1tr "${strFlHint}"*"bkp" |tail -n 1)"&&:
	local lstrFlNewest="$(ls -1 "${strFlHint}"*"bkp" |sort |tail -n 1)"&&:
	declare -p lstrFlNewest
	
	if [[ -n "$lstrFlNewest" ]];then
		local lnIndex="${lstrFlNewest#${strFlHint}.}"
		lnIndex="${lnIndex%.bkp}"
		lnIndex=$((10#$lnIndex))
		((lnIndex++))&&: #next
		declare -p lnIndex
		lnCount=$lnIndex
	fi
	
	while true;do 
		local lnSzNew=$(stat -c %s "$strFlHint");
		if(( lnSz != lnSzNew ));then
			local lstrIndex="$(printf %09d $lnCount)"
			cp -vf "$strFlHint" "${strFlHint}.${lstrIndex}.bkp";
			FUNCstringsDump "${lstrIndex}"
			((lnCount++))&&:;
			ls -l "$strFlHint"*"${lstrIndex}"*;
			lnSz=$lnSzNew;
		fi;
		sleep ${lfLoopDelay};
	done
};export -f FUNCmonitorChanges

if [[ "${1-}" == -m ]];then #help monitor changes and dump strings
	#FUNCmonitorChanges
	(xterm -e FUNCmonitorChanges & disown)
	exit
fi

export nScrWhalf=$(($(xdotool getdisplaygeometry |awk '{print $1}') / 2 ))

function FUNCpauseAfterLoad() {
	set -x
	: ${strTextHint:="hltv_status"} #help this shows up on the last writing to that file, after that you only need to wait for 5s!
	: ${bPauseOnlyNoFocusInstance:=false} #help :D
	while true;do
		nThisRunTime=$(date +%s)
		while true;do
			sleep 1
			
			anPid=($(pgrep -f "C:[\].*[\]mm.exe"))
			
			: ${bExitIfGameExits:=false} #help
			if $bExitIfGameExits;then
				if ! ps -p ${anPid[@]};then exit;fi
			fi
			
			if(( $(stat -c %Y "$strFlHint") < nThisRunTime ));then
				continue
			fi
			if ! egrep "${strTextHint}" "$strFlHint";then
				continue;
			fi
			: ${fSleepAfterHintFound:=3.0} #help
			read -n 1 -t $fSleepAfterHintFound -p "hit a key to SIGSTOP game"
			
			FUNCdetectPidToPause
			for nPid in "${anPid[@]}";do
				if $bPauseOnlyNoFocusInstance && ((FUNCdetectPidToPause_nPidNoFocus != 0 && nPid != FUNCdetectPidToPause_nPidNoFocus));then continue;fi
				kill -SIGSTOP $nPid
				if which ScriptEchoColor;then echoc --say "Game Loaded";fi
				#while ! yad --title="DarkMessiah:helper" --text="Dark Messiah of MM\n Game Finished Loading\n SigStopped\n Continue NOW?" --geometry=1x1+$nScrWhalf+0 --undecorated;do :;done; # not --on-top because it cant be too small :(
				#while ! yad --geometry=1x1+$nScrWhalf+0 --title="DarkMessiah:helper" --center --no-buttons;do :;done; # not --on-top because it cant be too small :(
				yad --geometry=500x1+$nScrWhalf+0 --title="DarkMessiah:FinishedLoading" --on-top --no-buttons --no-focus #unable to popup below :(, it should not receive imediate focus but should be focusable!!! unable to prevent it starting --on-top, so keep it there; no buttons, just hold the flow here
				kill -SIGCONT $nPid
			done
			
			break # to update nThisRunTime for the next game load
		done
	done
};export -f FUNCpauseAfterLoad;

if ! pgrep -fa DarkMessiah_FUNCpauseAfterLoad;then
	(xterm -title DarkMessiah_FUNCpauseAfterLoad -e bash -c "FUNCpauseAfterLoad" & disown);
fi
