#!/bin/bash

# The Clear BSD License
#
# Copyright (c) 2026, Gussak<https://github.com/Gussak>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted (subject to the limitations in the disclaimer
# below) provided that the following conditions are met:
#
#      * Redistributions of source code must retain the above copyright notice,
#      this list of conditions and the following disclaimer.
#
#      * Redistributions in binary form must reproduce the above copyright
#      notice, this list of conditions and the following disclaimer in the
#      documentation and/or other materials provided with the distribution.
#
#      * Neither the name of the copyright holder nor the names of its
#      contributors may be used to endorse or promote products derived from this
#      software without specific prior written permission.
#
# NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE GRANTED BY
# THIS LICENSE. THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
# CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
# PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
# IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.


#we cant ex.: alias gskHurtMeFUNC hurtme, then use gskHurtMeFUNC 3, it wont work

while [[ ! -f "./allMergerScriptsGenericConfig.sh" ]];do cd ..;done; source "./allMergerScriptsGenericConfig.sh"; FUNCminiModInit "$@"

: ${nHurtMeLim:=28} #help beyond this limit, the player starts jumping/floating...

: ${strFlOut:="gskHMAliasesAndErasers.cfg"} #help
export strFlOut

strIgniteHM50Cmd="ent_fire !player ignite" #help override, every second is 10 damage, for 5s, we cant control the damage and the time. just for fun

function FUNCfillFile() {
	FUNCchkCfgScriptLineSz "${1-}"
	echo "${1-}" >>"$strFlOut"
}

function FUNCerasers() {
	local lstrMainEraser="$1";shift
	local lstrToEraseBN="$1";shift
	local lnFrom="$1";shift
	local lnTo="$1";shift
	
	local lstrEraser="alias ${lstrMainEraser} \""
	for((i=lnFrom;i<=lnTo;i++));do
		lstrEraser+="alias ${lstrToEraseBN}$(printf %03d $i);"
	done
	if [[ "$lstrMainEraser" == gskHMHurtmeEraser1of3 ]];then
		lstrEraser+="alias gskHurtme500;"
	fi
	lstrEraser+="\""
	FUNCchkCfgScriptLineSz "$lstrEraser"
	FUNCfillFile "$lstrEraser"
}

: ${bUseIgnite:=true} #help
function FUNCchkIgnite() {
	if((nHurtMeLim!=28));then FUNCexit 1 "needs more complex calc?";fi
}

function FUNChurmeLim() {
	local lnCount="$1"
	
	local lstrOut
	local j
	
	if $bUseIgnite;then
		FUNCchkIgnite
		#if(( (lnCount*nHurtMeLim) > 50 ));then
			#lstrOut+="${strIgniteHM50Cmd}; "
			#((lnCount--))&&:
		#fi
		if((lnCount>=2));then
			#lstrOut+="gskHurtme050; gskHurtme006; " # this is for 2x28=56 only
			lstrOut+="${strIgniteHM50Cmd}; gskHurtme006; " # this is for 2x28=56 only
			((lnCount-=2))&&:
		fi
	fi
	
	for((j=0;j<lnCount;j++));do
		lstrOut+="hurtme ${nHurtMeLim}; gskWait33ms; "
	done
	
	FUNCchkCfgScriptLineSz "$lstrOut"
	echo "$lstrOut"
}

echo >"$strFlOut" #init/trunc
FUNCfillFile "// AUTO GENERATED by $(basename "$0"), DO NOT EDIT "
for((i=1;i<=nHurtMeLim;i++));do #map hurtme without jumping is 28
	FUNCfillFile "alias gskHurtme$(printf %03d $i) \"hurtme $i\""
done
for((i=$((nHurtMeLim+1));i<=100;i++));do #map hurtme without jumping is 28, and needs a minimum wait to properly work
	#if((  i < (${nHurtMeLim}*1) ));then
		#FUNCfillFile "alias gskHurtme$(printf %03d $i) \"$(FUNChurmeLim 1); hurtme $(( i - nHurtMeLim*(1-1) ))\""
	#el
	if((  i < (${nHurtMeLim}*2) ));then
		if $bUseIgnite;then
			if((i<50));then
				FUNCfillFile "alias gskHurtme$(printf %03d $i) \"$(FUNChurmeLim 1); hurtme $(( i - nHurtMeLim*(2-1) ))\""
			else
				FUNCchkIgnite
				FUNCfillFile "alias gskHurtme$(printf %03d $i) \"${strIgniteHM50Cmd}; hurtme $(( i - 50 ))\""
			fi
		else
			FUNCfillFile "alias gskHurtme$(printf %03d $i) \"$(FUNChurmeLim 1); hurtme $(( i - nHurtMeLim*(2-1) ))\""
		fi
	elif((i < (${nHurtMeLim}*3) ));then
		FUNCfillFile "alias gskHurtme$(printf %03d $i) \"$(FUNChurmeLim 2); hurtme $(( i - nHurtMeLim*(3-1) ))\""
	elif((i < (${nHurtMeLim}*4) ));then
		FUNCfillFile "alias gskHurtme$(printf %03d $i) \"$(FUNChurmeLim 3); hurtme $(( i - nHurtMeLim*(4-1) ))\""
	fi
done
#FUNCfillFile "alias gskHurtme050 \"${strIgniteHM50Cmd}; \" // override, every second is 10 damage, for 5s, we cant control the damage and the time. just for fun"
FUNCfillFile
FUNCfillFile "// for each constitution level"
aiHP=(200 350 500)
for iHP in "${aiHP[@]}";do
	FUNCfillFile "alias gskHurtme${iHP} \"$( FUNChurmeLim $((${iHP}/${nHurtMeLim})) ); hurtme $(( ${iHP} - ((${iHP}/${nHurtMeLim})*${nHurtMeLim}) )); \""
done
#echo "alias gskHurtme350 \"$( FUNChurmeLim $((350/${nHurtMeLim})) ); hurtme $(( 350 - ((350/${nHurtMeLim})*${nHurtMeLim}) )); \"" >>"$strFlOut"
#echo "alias gskHurtme500 \"$( FUNChurmeLim $((500/${nHurtMeLim})) ); hurtme $(( 500 - ((500/${nHurtMeLim})*${nHurtMeLim}) )); \"" >>"$strFlOut"

FUNCfillFile
FUNCfillFile "// ERASERS"
FUNCerasers gskHMHurtmeEraser1of3 "gskHurtme"  1  33
FUNCerasers gskHMHurtmeEraser2of3 "gskHurtme" 34  66
FUNCerasers gskHMHurtmeEraser3of3 "gskHurtme" 67 100

################
FUNCfillFile
FUNCfillFile "// MANA REGEN HELPERS"
for((i=1;i<=10;i++));do
	FUNCfillFile "alias gskManaReg$(printf %03d $i) \"mm_player_time_to_add_mana 0.$(printf %02d $i)\""
done
FUNCerasers "gskManaRegEraser" "gskManaReg" 1 10

ls -l "$strFlOut"

FUNCrefreshMount
