#!/bin/bash

#	BSD 3-Clause License
#
#	Copyright (c) 2026, Gussak<https://github.com/Gussak>
#
#	Redistribution and use in source and binary forms, with or without
#	modification, are permitted provided that the following conditions are met:
#
#	1. Redistributions of source code must retain the above copyright notice, this
#		 list of conditions and the following disclaimer.
#
#	2. Redistributions in binary form must reproduce the above copyright notice,
#		 this list of conditions and the following disclaimer in the documentation
#		 and/or other materials provided with the distribution.
#
#	3. Neither the name of the copyright holder nor the names of its
#		 contributors may be used to endorse or promote products derived from
#		 this software without specific prior written permission.
#
#	THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#	AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#	IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
#	DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
#	FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
#	DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
#	SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
#	CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
#	OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
#	OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

while [[ ! -f "./allMergerScriptsGenericConfig.sh" ]];do cd ..;done; source "./allMergerScriptsGenericConfig.sh"; FUNCminiModInit "$@"

astrAliasList=()
iSimuIndex=0
function FUNCreplace() {
	# to replace
	local lstrReplaceWhatCmdID="${1}";shift
	local lstrReplaceWhatModelBN="${1}";shift
	local lstrReplaceWhatFolder="${1}";shift
	# to dup
	local lstrCopyFromModelFile="${1}";shift
	local lstrCopyFromRelatPath="${1}";shift
	local lnSummonHPCost="${1}";shift
	
	if [[ -z "$lstrCopyFromModelFile" ]];then
		echo "was not overriden yet: ${lstrReplaceWhatCmdID}"
		return
	fi
	
	local lstrPathVanillaAllFiles="${strVanillaAllExtractedFilesPath}/mm/${lstrCopyFromRelatPath}/"

	if [[ ! -f "${lstrPathVanillaAllFiles}/${lstrCopyFromModelFile}.mdl" ]];then
		FUNCechoInfo "[ERROR] file '${lstrPathVanillaAllFiles}/${lstrCopyFromModelFile}.mdl' not found, did you extract all vanilla files from all VPKs?"
		exit 1
	fi

	mapfile -t astrFl < <(cd "${lstrPathVanillaAllFiles}/"; find ./ -type f -maxdepth 1 -mindepth 1 |sed -r -e 's@^./(.*)@\1@g')
	#declare -p astrFl;exit
	local lstrFl
	for lstrFl in "${astrFl[@]}";do
		mkdir -vp "${lstrReplaceWhatFolder}"
		#TODO copy the original .qct file and apply a patch like: "take_replace_by"	"models/items/weapons/arrows/arrow_classic.mdl" (but for ammo nothing seems to work, may work with other things tho)
		local lstrFlTo="${lstrReplaceWhatFolder}/${lstrReplaceWhatModelBN}${lstrFl#${lstrCopyFromModelFile}}"
		if ! cp -vf "${lstrPathVanillaAllFiles}/$lstrFl" "$lstrFlTo";then
			declare -p lstrReplaceWhatCmdID lstrReplaceWhatModelBN lstrReplaceWhatFolder lstrCopyFromModelFile lstrCopyFromRelatPath
			FUNCechoInfo "ERROR: '${lstrPathVanillaAllFiles}/$lstrFl' '$lstrFlTo'"
			read -n 1
			exit 1
		fi
	done
	declare -p lstrReplaceWhatCmdID lstrReplaceWhatModelBN lstrReplaceWhatFolder lstrCopyFromModelFile lstrCopyFromRelatPath >"${lstrReplaceWhatFolder}/000readme-AutoGeneratedDontEdit-Simulating-${lstrCopyFromModelFile}-THRU-${lstrReplaceWhatModelBN}.txt"
	
	local lstrIndex="$(printf %03d $iSimuIndex)"
	local lstrAliasCreate="$(FUNCfixAlias "gskCreate${lstrIndex}_${lstrCopyFromModelFile}")"
	local lstrAliasSummon="$(FUNCfixAlias "gskSummonSim${lstrIndex}_${lstrCopyFromModelFile}")"
	astrAliasList+=( "alias ${lstrAliasCreate} \"Test_CreateEntity ${lstrReplaceWhatCmdID}\"")
	astrSummonList+=("alias ${lstrAliasSummon} \"${lstrAliasCreate}; gskHurtme$(printf %03d $lnSummonHPCost); gskSmnWORK\"")

	((iSimuIndex++))&&:
	
	return 0
}

astrFail=(
	"fail cant pickup" "quiver_guard"
	   "quiver_guard" "models/items/weapons/quiver_guard/" 100 
	"fail, no model and ends up as food and causes super lag"
	   "money01" "models/items/jewels/money/" 1
	"fail cant pickup"
	   "quiver_orc" "models/items/weapons/quiver_orc/" 100
	"fail cant pickup"
	   "arrow_bal_exp" "models/items/weapons/arrows/" 20
	"fail useless and look broken"
	   "l11_coin2" "models/props/archi/l11/" 1
	"fail: it spawns and can be pickup but is not detected as ammunition for the bow"
	   "arrow_classic" "models/items/weapons/arrows/" 5
	"fail: this item cannot be spawned with give nor test_createentity. it spawns wrong, unable to equip. wont work even with: take_replace_by models/items/armors/player_armors/player_armor_wizard.mdl"
		"player_armor_wizard" "models/items/armors/player_armors/" 0
)
nInputParamsSz=6
astrInputParams=( #TODO remove the useless to free the very limited slots
	# It seems to work well ONLY for things that can only be grabbed to be thrown.
	# Items that could be taken to inventory fail even with this at qct file ex.: "take_replace_by"	"models/items/weapons/quiver_guard/quiver_guard.mdl" (but may work with other things than arrow or quiver (that have no inventory item are just ammo))
	
	# COLUMNS
	#lstrReplaceWhatCmdID      lstrReplaceWhatModelBN	lstrReplaceWhatFolder	           lstrCopyFromModelFile	lstrCopyFromRelatPath
	
	############## KEEP OVERRIDEN ON TOP and do NOT change their order as will be indexed, to not break other usages...
	"item_food_bread02_cooked" "bread02_cooked"  "models/items/provisions/bread02/"  "l6_jar_oil"  "models/props/furnitures/gob/l6_jar_oil/" 100
	"item_food_bread02_row"    "bread02_raw"     "models/items/provisions/bread02/"  "barrel01"     "models/props/furnitures/humans/" 100
	"item_food_green_apple"    "green_apple"     "models/items/provisions/fruit/"    "l11_coin" "models/props/archi/l11/" 500 #aim on floor, useful to create indestructible low barriers, unable to jump over, good for changing map areas access thru gskmap
	"item_food_leek03"         "leek03"          "models/items/provisions/leeks/"    "stool01" "models/props/furnitures/humans/" 500 #can be used to provide infinite fire arrows thru fire spell on it
	"item_food_egg"            "egg"             "models/items/provisions/egg/"        "axe" "models/items/weapons/axes/" 0 # this item cannot be spawned with give nor test_createentity. It spawns different (weaker) but may suffice...
	
	############## testing

#	.qct tests
#		"take_replace_by"	"models/items/weapons/arrows/arrow_classic.mdl"		
#		"take_replace_by"	"models/items/weapons/quiver_guard/quiver_guard.mdl"
	
	############## NOT OVERRIDEN
	"item_food_garlic_piece01" "garlic_b1"       "models/items/provisions/garlic/"   "" "" 0
	"item_food_garlic_piece02" "garlic_b2"       "models/items/provisions/garlic/"   "" "" 0
	"item_food_mushroom_medium" "mushroom_medium" "models/items/provisions/mushroom/"  "" "" 0
	"item_food_garlic_piece03" "garlic_b3"       "models/items/provisions/garlic/"   "" "" 0
	"item_food_leek02"         "leek02"          "models/items/provisions/leeks/"    "" "" 0
	"item_food_leeks"          "leeks"           "models/items/provisions/leeks/"    "" "" 0
	"item_food_mushroom_small"  "mushroom_small"  "models/items/provisions/mushroom/"  "" "" 0
	"item_food_red_apple"       "red_apple"       "models/items/provisions/fruit/"     "" "" 0
	"item_food_saucisson"       "saucisson01"     "models/items/provisions/saucisson/" "" "" 0
	# "" "" 0
	
	"item_food_bread01_row" "bread01_raw" "models/items/provisions/bread01/" "" "" 0 #this one has model but is useless, cant be baked
	
	#"item_food_fish01" "fish01" "models/items/provisions/fish/" "quiver_guard"  "models/items/weapons/quiver_guard/" 100 #TODO: REMOVE THIS AS IT WORKS OK!!! IS JUST A TEST!!! btw, doesnt work take_replace_by for arrow nor quiver (may be because they are ammo and not storable items)
	
	######################## DO NOT USE #################################
	"item_food_food_ratio01"   "food_ratio01"    "models/items/provisions/food_ratio/" "" "" 0 #DO NOT USE!!! it is hardcoded and always become food!!!!
)
if(( (${#astrInputParams[@]}%nInputParamsSz) != 0 ));then
	FUNCechoInfo "[DevERROR] invalid param count ${#astrInputParams[@]} % $nInputParamsSz = $((${#astrInputParams[@]}%nInputParamsSz))"
	exit 1
fi
mapfile -t astrDetectedDB < <(cat "${strPathMainModFolder}/_mods/BloodySummoner/content/cfg/bloodysummoner.cfg" |egrep "^//ERROR:MissingMDL:" |sed -r -e 's@.*MissingMDL:(.*)[/]([^/]*)[.]mdl.*Test_CreateEntity ([^;]*);.*@"\3" "\2" "\1/" "" ""@g')
#declare -p astrDetectedDB
#astrRemainingDetectedDB=()

if FUNCaskYesNo "Trashing models folder";then
	trash models&&:
fi

for((i=0;i<${#astrInputParams[@]};i+=nInputParamsSz));do
	FUNCreplace "${astrInputParams[@]:$i:$nInputParamsSz}"
	#bFound=false
	for((j=0;j<${#astrDetectedDB[@]};j++));do
		#declare -p j astrDetectedDB
		if [[ "${astrDetectedDB[$j]}" =~ .*${astrInputParams[$i]}.* ]];then
			unset astrDetectedDB[$j]
			#bFound=true
			break
		fi
	done
	astrDetectedDB=("${astrDetectedDB[@]}")
	#if ! $bFound;then astrRemainingDetectedDB+=();fi
done
#if(( ${#astrDetectedDB[@]} != (${#astrInputParams[@]}/nInputParamsSz) ));then

if(( ${#astrDetectedDB[@]} > 0 ));then
	echo
	echo "[INFO] new free slots were detected and documented:"
	for strLn in "${astrDetectedDB[@]}";do
		echo "$strLn"
	done
	echo
fi
#fi

mkdir -vp cfg
strFlCfg="cfg/gskSummonSimulatedThings.cfg"
echo >"${strFlCfg}" #trunc/init
echo "// AUTO GEN BY $(basename "$0")" >>"${strFlCfg}"
#for strAlias in "${astrAliasList[@]}";do
for((i=0;i<${#astrAliasList[@]};i++));do
	echo "${astrAliasList[i]}" >>"${strFlCfg}"
	echo "${astrSummonList[i]}" >>"${strFlCfg}"
done
echo >>"${strFlCfg}"
#echo "# now place the above aliases in some mod, suggestion: BloodySummoner (will go to a summon list) and may be gskCustomBinds (but already on ${strFlCfg})"

echo
FUNCrefreshMount # after changes
echo

cat "${strFlCfg}"
echo
ls -l "${strFlCfg}"

echo "now run:"
echo "(cd '$strPathMainModFolder/_mods/MultiplyEnemies/content/cfg/'; ./createNpcSpawnSwitches.sh) #to update summon list"
